[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=alphagradient"
testpaths = [
    "test",
]

[mypy]
ignore_missing_imports = true